#!/bin/bash
# Taken from:
#	https://raw.github.com/kaihendry/Kai-s--HOME/master/.xinitrc
#
# for terminus font in Archlinux :(
#
# Todo
# Add battery status :
# 	upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | something


xset +fp /usr/share/fonts/local
xset fp rehash

xset -b # disable bell

while true
do
	VOL=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
	LOCALTIME=$(date +%Z\:%Y-%m-%dT%H:%M)
	OTHERTIME=$(TZ=America/Argentina/Buenos_Aires date +%Z\:%H:%M)
	IP2=$(curl icanhazip.com)
	IP=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -n1) # can get confused if you use vmware
	TEMP="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))C"
	BAT2="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage)"

	if acpi -a | grep off-line > /dev/null
	then
		BAT="Bat. $(acpi -b | awk '{ print $4 " " $5 }' | tr -d ',')"
		xsetroot -name "WAN:$IP2 LAN:$IP $BAT $VOL $TEMP $LOCALTIME $OTHERTIME"
	else
		xsetroot -name "WAN:$IP2 LAN:$IP ${BAT2:25:4} $VOL $TEMP $LOCALTIME $OTHERTIME"
	fi
	sleep 20s
done &

while true
do
	feh --bg-fill http://www.lutherlabs.com/files/hex-000097.png
done &

xautolock -time 2 -locker slock &
gnome-terminal &
chromium-browser &

exec dwm
