#!/bin/bash
# Mostly taken from:
#	https://raw.github.com/kaihendry/Kai-s--HOME/master/.xinitrc

xset +fp /usr/share/fonts/local
xset fp rehash
xset -b # disable bell
feh --bg-fill /home/f1nch/Pictures/wallpaper.jpg

while true
do
	VOL=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
	LOCALTIME=$(date +%Z\:%Y-%m-%dT%H:%M)
	OTHERTIME=$(TZ=America/Argentina/Buenos_Aires date +%Z\:%H:%M)
	IP2=$(curl icanhazip.com)
	IP=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -n1)
	TEMP=$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))
	if acpi -a | grep off-line > /dev/null
	then
		#TODO - Add check for discharging battery, only display that battery.
		BAT1=$(acpi -b | grep "Battery 0" | awk '{ print $4 }' | sed 's/,//')
		DUR1=$(acpi -b | grep "Battery 0" | awk '{ print $5 }')
		BAT2=$(acpi -b | grep "Battery 1" | awk '{ print $4 }' | sed 's/,//')
		DUR2=$(acpi -b | grep "Battery 1" | awk '{ print $5 }')
		xsetroot -name "WAN:$IP2 LAN:$IP B1:$BAT1 B2:$BAT2 $VOL $TEMP $LOCALTIME"
	else
		xsetroot -name "WAN:$IP2 LAN:$IP ${BAT2:25:4} $VOL $TEMP $LOCALTIME"
	fi
	sleep 20s
done &

gnome-terminal &
chromium-browser &

exec dwm
