#!/bin/bash

MODE=$(echo $1 | awk '{ print tolower($0) }')

if [ $MODE == "work" ]; then
  echo "Work"
  xrandr \
    --output DP-1 --mode 1920x1080 --pos 3840x0 \
    --output DP-2 --mode 1920x1080 --pos 1920x420 \
    --output HDMI-1 --mode 1920x1080 --pos 0x420
  # nohup latte-dock --replace &
elif [ $MODE == "play" ]; then
  echo "Play"
  xrandr \
    --output DP-1 --mode 1920x1080 --pos 5760x0 \
    --output DP-2 --mode 3840x2160 --pos 1920x0 \
    --output HDMI-1 --mode 1920x1080 --pos 0x540
  # nohup latte-dock --replace &
else
  echo "Play"
  xrandr \
    --output DP-1 --mode 1920x1080 --pos 5760x0 \
    --output DP-2 --mode 3840x2160 --pos 1920x0 \
    --output HDMI-1 --mode 1920x1080 --pos 0x540
  # nohup latte-dock --replace &
fi


